### ISSUE TITLE
Randomly failing sbt tests

### ISSUE THREAD

**Issue by lubarskyy** [softwaremill/adopt-tapir#116]
From time to time one of the sbt tests fails, combination of (Scala3, Circle) - https://github.com/softwaremill/adopt-tapir/runs/7742550077?check_suite_focus=true, usually rerunning the job helps the situation, but randomly failing tests are non-deterministic and hard to work with. Maybe there is some kind of race condition between jobs :thinking:.

similar cases of occurence:
- https://github.com/softwaremill/adopt-tapir/actions/runs/2803866353

**Comment by geminicaprograms** [comment]
Last two times it was `Verify (Scala3, Circe)` job but configuration varies. Let's keep an eye on what is failing.

**Comment by adamw** [comment]
I think this stopped being a problem
