### ISSUE TITLE
[Optimization] Use internal cache for generated zip files

### ISSUE THREAD

**Issue by marcin-jozefowicz** [softwaremill/adopt-tapir#126]
# Description
Instead of generation zip file for every request. Introduce backend internal cache which will gnerate zip file or reuse previously created zip file sligthly modifying the packages and project name. 

It should dramaticallly lower our response from ~3s.

**Comment by adamw** [comment]
Closing as this only impacts the first request after a restart, otherwise the generation is fast. And this would mean a rewrite of most of the project.
