### ISSUE TITLE
Few tweaks to the structure generated for Scala CLI

### ISSUE THREAD

**Issue by romanowski** [softwaremill/adopt-tapir#194]
I need to say that the project is amazing, and the generated structure for Scala CLI is good. Since we haven't created a recommended structure for such projects yet, adopt-tapir is the perfect opportunity to create it ;)

To kick off discussion, I created [a repo](https://github.com/romanowski/adopt-tapir-scala-cli-example/tree/master) where I track all the changes that I think should be made in the structure (if people agree I think I should be able to open PR to the tool changing the structure. Summary of change:
 - .gitignore mainly  to exclude `.scala-build` and `.bsp` directories
 - Use comment based using directives - other forms are not recommended for now and confuse Intellij / Metals. Metals nicely colors the comment based directives
 -  Use `*.scala` files in project definition not to confuse metals / IntelliJ
 - Add a bit to Readme about opening the project in IDE

**Comment by geminicaprograms** [comment]
> 

Thanks for the feedback I really appreciate it 😃 
I generally agree and can perform the necessary changes in the code but I would leave the `.gitignore` out of the discussion for the time being as it is not generated for `sbt` either. IOW it is a feature itself and IMHO it should be better to introduce it for both `build tools`.

**Comment by geminicaprograms** [comment]
Having said that I believe that we could join the efforts and I could prepare the PR (as I know the code better) and you could test it, @romanowski WDYT?
