### ISSUE TITLE
fix: minor glitches in Preview screen implementation

### ISSUE THREAD

**Issue by geminicaprograms** [softwaremill/adopt-tapir#219]
Look and feel:
* when screen estate is smaller then styling is not consistent e.g.:
  <img width="382" alt="image" src="https://user-images.githubusercontent.com/3641082/194855772-6ea4cbf3-ed53-46b7-a96a-663bb5e6c805.png">

Composition:
* it is a bit counter-intuitive to navigate between `preview` components implementation in order to understand/provide more functionality, maybe there is already existing `tree-view` structure that could be used instead?

**Comment by marekhuckmann** [comment]
The 'look and feel' part was easy: #220 

Composition part:
A lot of work has been put into the custom tree-view functionality.
Unfortunately, the already existing [MUI's React Tree View](https://mui.com/material-ui/react-tree-view/) hasz not been used here and therefore out version is not as well documented and may seem complicated.

I see 2 solutions here:
1. Document the current tree-view implementation
2. Use MUI's React Tree View - parse the JSON coming from server in a similar way as here: [MUI's demo](https://codesandbox.io/s/i9ndqj?file=/demo.tsx) and style the tree accordingly.

**Comment by geminicaprograms** [comment]
If, from the maintenance point of view (considering the documentation and the fact that existing components don't have to be tested, etc...) it would be _cheaper_ to rely on MUI's Tree View I would favour the solution `2.`...
