### ISSUE TITLE
RFC: cache locally couple of last starter configurations on the frontend side

### ISSUE THREAD

**Issue by lubarskyy** [softwaremill/adopt-tapir#35]
# Overview
List 5-6 most recent successful configuration generations under the configuration form. Data that is being send as a response to `/starter.zip` request is in binary format, on the frontend side we do wrap it using the [Blob API](https://developer.mozilla.org/en-US/docs/Web/API/Blob), this allows us to keep raw data in storages like `localStorage` or `sessionStorage`.

Visual representation of such solution might be a simple list with the file name +  human readable timestamp of generation. Hovering over each entry would list selected options used to generate configuration. Upon user clicking the entry row or some icon user would be able download `.zip` file without need of additional request.

# Motivation
As a developer I want to have a quick access to last configurations in order not to fill the form again if the setting that I use the most doesn't change.

# Pitfalls
As the project emerges some options might change and potentially make the cached version of some configuration variation not usable.

**Comment by adamw** [comment]
So this would be local-only? This brings into scope cookies and disclaimers once again ;)

**Comment by lubarskyy** [comment]
We would only store a raw binary data + payload that was send to the backend, there are no personal information like IP address etc. Nothing that can be used to target users.

**Comment by lubarskyy** [comment]
@adamw if you do not see the use for such a feature right now, we can close this RFC :)

**Comment by lubarskyy** [comment]
Closing due to RFC not getting a community interest.
