### ISSUE TITLE
Deprecation warning in Adopt Tapir starter project (ZIO + http4s)

### ISSUE THREAD

**Issue by beneyal** [softwaremill/adopt-tapir#374]
Hello,

When creating an Adopt Tapir project with this config:
![image](https://github.com/softwaremill/tapir/assets/3891274/fcc6f607-4c28-4ecf-be28-0ffa09bdd623)

I get the following deprecation warning when compiling (no changes to the template whatsoever):
![image](https://github.com/softwaremill/tapir/assets/3891274/1e5c22ad-4a1f-4e1d-b058-8cc4d47bd721)

I haven't been able to find anything related to it, nor do I know which library is causing this.

What I can say is that this warning is probably related to Ember, as Blaze server did not raise such a warning.

Thanks!

**Comment by adamw** [comment]
Thanks for the report, we'll look into that. I've moved the issue to the adopt-tapir project itself :)

**Comment by beneyal** [comment]
Ah! Progress! https://github.com/zio/interop-cats/issues/667
Seems like a fix was merged, so now I guess it's a matter of waiting for a release 😃

**Comment by PanHNE** [comment]
The new version has been released and the warning does not appear anymore.

**Comment by beneyal** [comment]
Sorry for the late reply, but the exact same deprecation notice still appears for me in a newly generated Adopt Tapir project using ZIO and http4s.

**Comment by adamw** [comment]
Reopening then

**Comment by beneyal** [comment]
I don't know if this counts as a solution or not, but after tinkering around a bit, I found that this import (from `zio-interop-cats`) makes the deprecation warning go away:

```scala
import zio.stream.interop.fs2z.io.*
```

**Comment by adamw** [comment]
cc @PanHNE ^

**Comment by PanHNE** [comment]
@beneyal We added more specific import which removes the warning. Could you check it and confirm?
