### ISSUE TITLE
Add alerts into slack channel (optionally with use of graphana)

### ISSUE THREAD

**Issue by marcin-jozefowicz** [softwaremill/adopt-tapir#43]
## Background
Currently our app doesn't have any alerting when something will go wrong.
In near future there will be Graphana created. Consider using it (if it is not created prepare all required things ahead. )

## Acceptance criteria
- all critical and major issues are added on separate slack channel 
- fulfill documentation at KiWi

**Comment by geminicaprograms** [comment]
The low hanging fruit was to create an alert based on logs (functionality available in our cloud provider) and send it to a dedicated slack channel - see the corresponding commit for details if that is for now good enough.

**Comment by geminicaprograms** [comment]
As discussed internally information about logs and alerts was added to the KiWI.
